/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.robertob.p2ipc1.frames;
import com.robertob.p2ipc1.engine.*;
import com.robertob.p2ipc1.utils.list.DoubleLinkedListException;

/**
 *
 * @author robertob
 */
public class ControlStationInternalFrame extends javax.swing.JInternalFrame {

    ControlStation frameControlStation;
    Simulation currentSimulation;
    
    public ControlStationInternalFrame(ControlStation frameControlStation, Simulation currentSimulation) {
        this.frameControlStation = frameControlStation;
        this.currentSimulation = currentSimulation;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        controlStationId = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        conectedPlanesLbl = new javax.swing.JLabel();
        maxPlanesLbl = new javax.swing.JLabel();
        planeIdComboBox = new javax.swing.JComboBox<>();
        trackIdComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        assignTrackToPlane = new javax.swing.JButton();
        updateComboBoxes = new javax.swing.JButton();
        approveLandingToPlane = new javax.swing.JButton();

        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 21)); // NOI18N
        jLabel1.setText("ESTACIÓN DE CONTROL:");

        controlStationId.setFont(new java.awt.Font("Open Sans", 1, 21)); // NOI18N
        controlStationId.setText("#ID");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel3.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N
        jLabel3.setText("LISTA DE LLAMADAS");

        jLabel4.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N
        jLabel4.setText("ASIGNACIÓN DE PISTAS");

        jLabel5.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel5.setText("Aviones comunicados a esta torre:");

        jLabel6.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel6.setText("Maxima capacidad de esta torre:");

        conectedPlanesLbl.setFont(new java.awt.Font("Open Sans", 1, 16)); // NOI18N
        conectedPlanesLbl.setText("9999");

        maxPlanesLbl.setFont(new java.awt.Font("Open Sans", 1, 16)); // NOI18N
        maxPlanesLbl.setText("9999");

        jLabel7.setFont(new java.awt.Font("Open Sans", 2, 14)); // NOI18N
        jLabel7.setText("#ID Avión");

        jLabel9.setFont(new java.awt.Font("Open Sans", 2, 14)); // NOI18N
        jLabel9.setText("#ID Pista");

        assignTrackToPlane.setBackground(new java.awt.Color(51, 255, 153));
        assignTrackToPlane.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        assignTrackToPlane.setForeground(new java.awt.Color(51, 51, 51));
        assignTrackToPlane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/p2ipc1/images/changeBlack.png"))); // NOI18N
        assignTrackToPlane.setText("Asignar");
        assignTrackToPlane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        assignTrackToPlane.setMargin(new java.awt.Insets(2, 6, 2, 6));
        assignTrackToPlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignTrackToPlaneActionPerformed(evt);
            }
        });

        updateComboBoxes.setBackground(new java.awt.Color(255, 204, 204));
        updateComboBoxes.setFont(new java.awt.Font("Open Sans", 1, 13)); // NOI18N
        updateComboBoxes.setForeground(new java.awt.Color(51, 51, 51));
        updateComboBoxes.setText("Actualizar");
        updateComboBoxes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateComboBoxes.setMargin(new java.awt.Insets(2, 4, 2, 4));
        updateComboBoxes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateComboBoxesActionPerformed(evt);
            }
        });

        approveLandingToPlane.setBackground(new java.awt.Color(255, 255, 153));
        approveLandingToPlane.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        approveLandingToPlane.setForeground(new java.awt.Color(51, 51, 51));
        approveLandingToPlane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/p2ipc1/images/landingTrackBlack.png"))); // NOI18N
        approveLandingToPlane.setText("Aprobar aterrizaje");
        approveLandingToPlane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        approveLandingToPlane.setMargin(new java.awt.Insets(2, 6, 2, 6));
        approveLandingToPlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveLandingToPlaneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(planeIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(trackIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(updateComboBoxes, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(approveLandingToPlane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(assignTrackToPlane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(controlStationId))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(conectedPlanesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(maxPlanesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(controlStationId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(conectedPlanesLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(maxPlanesLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(updateComboBoxes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(planeIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(trackIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(26, 26, 26)
                        .addComponent(assignTrackToPlane, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(approveLandingToPlane, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateComboBoxesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateComboBoxesActionPerformed
        planeIdComboBox.removeAllItems();
        trackIdComboBox.removeAllItems();
        try {
            for (int i = 0; i < frameControlStation.getPlanesOnControlStation().length(); i++) {
            planeIdComboBox.addItem(String.valueOf(frameControlStation.getPlanesOnControlStation().get(i).getPlaneId()));
            }
            for (int i = 0; i < currentSimulation.getLandingTracks().length(); i++) {
                trackIdComboBox.addItem(String.valueOf(currentSimulation.getLandingTracks().get(i).getId()));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_updateComboBoxesActionPerformed

    private void assignTrackToPlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignTrackToPlaneActionPerformed
        Plane planeToAssign = null;
        LandingTrack trackToAssign = null;
        try {
            planeToAssign = this.currentSimulation.getPlaneById(Integer.parseInt((String)this.planeIdComboBox.getSelectedItem()));
            trackToAssign = this.currentSimulation.getTrackById(Integer.parseInt((String)this.trackIdComboBox.getSelectedItem()));
        } catch (Exception e) {   
        }
        this.frameControlStation.planeLandingAssignation(planeToAssign, trackToAssign);
    }//GEN-LAST:event_assignTrackToPlaneActionPerformed

    private void approveLandingToPlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveLandingToPlaneActionPerformed
        Plane planeToApprove = null;
        try {
            planeToApprove = this.currentSimulation.getPlaneById(Integer.parseInt((String)this.planeIdComboBox.getSelectedItem()));
        } catch (Exception e) {
        }
        this.frameControlStation.planeLandingApproval(planeToApprove);
    }//GEN-LAST:event_approveLandingToPlaneActionPerformed

    public void updateControlStationFrame() throws DoubleLinkedListException {
        controlStationId.setText(String.valueOf(this.frameControlStation.getId()));
        // Actualiza cantidad de aviones conectados y maximos
        conectedPlanesLbl.setText(String.valueOf(frameControlStation.getConectedPlanes()));
        maxPlanesLbl.setText(String.valueOf(frameControlStation.getMaxPlanes()));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveLandingToPlane;
    private javax.swing.JButton assignTrackToPlane;
    private javax.swing.JLabel conectedPlanesLbl;
    private javax.swing.JLabel controlStationId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel maxPlanesLbl;
    private javax.swing.JComboBox<String> planeIdComboBox;
    private javax.swing.JComboBox<String> trackIdComboBox;
    private javax.swing.JButton updateComboBoxes;
    // End of variables declaration//GEN-END:variables
}
