/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.robertob.p2ipc1.frames;

import com.robertob.p2ipc1.engine.Simulation;
import com.robertob.p2ipc1.engine.MaintenanceStation;
import com.robertob.p2ipc1.engine.Plane;
import com.robertob.p2ipc1.utils.list.DoubleLinkedListException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author robertob
 */
public class MaintenanceStationsInternalFrame extends javax.swing.JInternalFrame {

    Simulation currentSimulation;
    
    public MaintenanceStationsInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        maintenanceStationsTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        maintenanceStationSelector = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setResizable(true);
        setPreferredSize(new java.awt.Dimension(550, 530));

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 21)); // NOI18N
        jLabel1.setText("ESTACIONES DE MANTENIMIENTO");

        jScrollPane1.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N

        maintenanceStationsTable.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        maintenanceStationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "ID Avion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        maintenanceStationsTable.setRowHeight(50);
        maintenanceStationsTable.setShowGrid(true);
        jScrollPane1.setViewportView(maintenanceStationsTable);

        jButton1.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        jButton1.setText("Actualizar");
        jButton1.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        maintenanceStationSelector.setFont(new java.awt.Font("Open Sans", 0, 17)); // NOI18N
        maintenanceStationSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceStationSelectorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        jLabel2.setText("Ver pista:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(maintenanceStationSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(maintenanceStationSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        updateMaintenanceStationSelector();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void maintenanceStationSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceStationSelectorActionPerformed
        try {
            updateMaintenanceStationTable();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_maintenanceStationSelectorActionPerformed

    public void updateMaintenanceStationSelector() {
        maintenanceStationSelector.removeAllItems();
        try {
            for (int i = 0; i < this.currentSimulation.getMaintenanceStations().length(); i++) {
                maintenanceStationSelector.addItem(String.valueOf(this.currentSimulation.getMaintenanceStations().get(i).getId()));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
       
    }
    
    private void updateMaintenanceStationTable() throws DoubleLinkedListException {
        DefaultTableModel maintanceDefaultTableModel = (DefaultTableModel)this.maintenanceStationsTable.getModel();
        MaintenanceStation maintenanceStationToShow = null;
        maintenanceStationToShow = this.currentSimulation.getMaintenanceStationById(Integer.parseInt((String)this.maintenanceStationSelector.getSelectedItem()));
        maintanceDefaultTableModel.setRowCount(0);
        for (int i = 0; i < maintenanceStationToShow.getPlanesOnMaintenanceQueue().length(); i++) {
            if ((maintenanceStationToShow.getPlanesOnMaintenanceQueue().get(i).getPlaneState() == Plane.PLANE_STATE.ON_MAINTENANCE) 
                 || (maintenanceStationToShow.getPlanesOnMaintenanceQueue().get(i).getPlaneState() == Plane.PLANE_STATE.WAITING_MAINTENANCE)) {
                maintanceDefaultTableModel.addRow(maintenanceStationToShow.getPlanesOnMaintenanceQueue().get(i).toAlternateTableFormat());
            }
        }
    }
    
    public JTable getMaintenanceStationsTable() {
        return maintenanceStationsTable;
    }

    public void setCurrentSimulation(Simulation currentSimulation) {
        this.currentSimulation = currentSimulation;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> maintenanceStationSelector;
    private javax.swing.JTable maintenanceStationsTable;
    // End of variables declaration//GEN-END:variables

    

    
}
