/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.robertob.p2ipc1.frames;


/**
 *
 * @author robertob
 */
public class SetTimesDialog extends javax.swing.JDialog {

    private int CONSUME_FUEL_TIME;
    private int LANDING_TIME;
    private int DISEMBARKING_TIME;
    private int MAINTENANCE_TIME;
    private int TAKE_OFF_TIME;
    private MainFrame mainFrame;
    
    public SetTimesDialog(java.awt.Frame parent, boolean modal, MainFrame mainFrame) {
        super(parent, modal);
        initComponents();
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        consumeFuelSpnr = new javax.swing.JSpinner();
        landingSpnr = new javax.swing.JSpinner();
        disembarkingSpnr = new javax.swing.JSpinner();
        maintenanceSpnr = new javax.swing.JSpinner();
        takeOffSpnr = new javax.swing.JSpinner();
        continueBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 21)); // NOI18N
        jLabel1.setText("CONFIGURAR TIEMPOS (EN MILISEGUNDOS)");

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 20)); // NOI18N
        jLabel2.setText("Gastar un galon de combustible");

        jLabel3.setFont(new java.awt.Font("Open Sans", 0, 20)); // NOI18N
        jLabel3.setText("Aterrizaje");

        jLabel4.setFont(new java.awt.Font("Open Sans", 0, 20)); // NOI18N
        jLabel4.setText("Desabordaje (por pasajero)");

        jLabel5.setFont(new java.awt.Font("Open Sans", 0, 20)); // NOI18N
        jLabel5.setText("Mantenimiento");

        jLabel6.setFont(new java.awt.Font("Open Sans", 0, 20)); // NOI18N
        jLabel6.setText("Despegue");

        consumeFuelSpnr.setFont(new java.awt.Font("Open Sans", 2, 20)); // NOI18N
        consumeFuelSpnr.setModel(new javax.swing.SpinnerNumberModel(1000, 1000, null, 1));

        landingSpnr.setFont(new java.awt.Font("Open Sans", 2, 20)); // NOI18N
        landingSpnr.setModel(new javax.swing.SpinnerNumberModel(1000, 1000, null, 1));

        disembarkingSpnr.setFont(new java.awt.Font("Open Sans", 2, 20)); // NOI18N
        disembarkingSpnr.setModel(new javax.swing.SpinnerNumberModel(1000, 1000, null, 1));

        maintenanceSpnr.setFont(new java.awt.Font("Open Sans", 2, 20)); // NOI18N
        maintenanceSpnr.setModel(new javax.swing.SpinnerNumberModel(1000, 1000, null, 1));

        takeOffSpnr.setFont(new java.awt.Font("Open Sans", 2, 20)); // NOI18N
        takeOffSpnr.setModel(new javax.swing.SpinnerNumberModel(1000, 1000, null, 1));

        continueBtn.setBackground(new java.awt.Color(0, 204, 153));
        continueBtn.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N
        continueBtn.setForeground(new java.awt.Color(51, 51, 51));
        continueBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/p2ipc1/images/nextBlack.png"))); // NOI18N
        continueBtn.setText("Continuar");
        continueBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        continueBtn.setIconTextGap(1);
        continueBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));
        continueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(takeOffSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(maintenanceSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(disembarkingSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(landingSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(116, 116, 116)
                                .addComponent(consumeFuelSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(continueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(consumeFuelSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(landingSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(disembarkingSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(maintenanceSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(takeOffSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(continueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBtnActionPerformed
        this.CONSUME_FUEL_TIME = (int)consumeFuelSpnr.getValue();
        this.LANDING_TIME = (int)landingSpnr.getValue();
        this.DISEMBARKING_TIME = (int)disembarkingSpnr.getValue();
        this.MAINTENANCE_TIME = (int)maintenanceSpnr.getValue();
        this.TAKE_OFF_TIME = (int)takeOffSpnr.getValue();
        this.dispose();
        this.mainFrame.getCurrentSimulation().setTimes(this.CONSUME_FUEL_TIME, this.LANDING_TIME, this.DISEMBARKING_TIME, this.MAINTENANCE_TIME, this.TAKE_OFF_TIME);
        this.mainFrame.getLoadFilesDialog().setVisible(true);
        
    }//GEN-LAST:event_continueBtnActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner consumeFuelSpnr;
    private javax.swing.JButton continueBtn;
    private javax.swing.JSpinner disembarkingSpnr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSpinner landingSpnr;
    private javax.swing.JSpinner maintenanceSpnr;
    private javax.swing.JSpinner takeOffSpnr;
    // End of variables declaration//GEN-END:variables

    public int getCONSUME_FUEL_TIME() {
        return CONSUME_FUEL_TIME;
    }

    public int getLANDING_TIME() {
        return LANDING_TIME;
    }

    public int getDISEMBARKING_TIME() {
        return DISEMBARKING_TIME;
    }

    public int getMAINTENANCE_TIME() {
        return MAINTENANCE_TIME;
    }

    public int getTAKE_OFF_TIME() {
        return TAKE_OFF_TIME;
    }
}
